version: '3.9'
services:
  postgres:
    image: postgres:16.3-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=yoggerGod
      - POSTGRES_PASSWORD=dQ4SXE2WYu4ZpvvZ4q6U
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: